name: CI Build and Test with Docker

on:
  push:
    branches:
      - master
    paths:
      - '**.cs'
      - '**.csproj'
      - 'Dockerfile'
  pull_request:
    branches:
      - master
    paths:
      - '**.cs'
      - '**.csproj'
      - 'Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test via Dockerfile
        run: docker build -t aspnet-sample .
