name: Project lints

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install TFLint
      run: |
        wget https://github.com/terraform-linters/tflint/releases/download/v0.23.0/tflint_linux_amd64.tar.gz
        tar -xvzf tflint_linux_amd64.tar.gz
        sudo mv tflint /usr/local/bin/

    - name: Install terraform fmt
      run: terraform fmt -recursive