name: Terraform AWS

on:
  pull_request:
    branches:
      - master
    paths:
      - "terraform/*"
      - ".github/workflows/terraform.yaml"

jobs:
  terraform-lints:
    name: Terraform Lint & Security Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout terraform source code
      uses: actions/checkout@v4

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.58.1

    - name: Setup tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        tfsec_version: v1.0.3
        additional_args: -m HIGH

    - name: Show version
      run: tflint --version

    - name: Run TFLint
      run: tflint -f compact

  terraform:
    name: Terraform Plan & Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform validate
      run: terraform -chdir=terraform validate

    - name: Terraform Plan
      run: terraform -chdir=terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      continue-on-error: true
    
    # - name: Terraform apply 
    #   run: terraform -chdir=terraform apply -auto-approve
