name: Project lints

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout terraform source code
      uses: actions/checkout@v1

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.58.1

    - name: Setup tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        tfsec_version: v1.0.3
        additional_args: -m HIGH

    - name: Show version
      run: tflint --version

    - name: Run TFLint
      run: tflint -f compact
  
